site_name: 疾风计划笔记
site_url: https://ernestearth.github.io/jifeng/
site_author: 南朔

theme:
  name: material
  # name: gitbook

nav:
  - 简介: index.md
  - 程序设计基础: Fundamentals_of_Programming/index.md
  - About: about.md