site_name: 疾风计划笔记
copyright: Copyright &copy; 南朔
site_description: "2024 年第三期疾风计划的学习笔记"
site_url: https://ernestearth.github.io/jifeng/
site_author: 南朔

nav:
  - 课程概览: index.md
  - 程设基础: 
    - 课程简介: Fundamentals_of_Programming/index.md
    - ch1 编程初步: Fundamentals_of_Programming/ch1.md
    - ch2 变量与代数思维: Fundamentals_of_Programming/ch2.md
    - ch3 逻辑推理与枚举: Fundamentals_of_Programming/ch3.md
    - ch4 筛法与查找: Fundamentals_of_Programming/ch4.md
    - ch5 分治思想与递归: Fundamentals_of_Programming/ch5.md
    - ch6 递推与动态规划: Fundamentals_of_Programming/ch6.md
    - ch7 文本数据处理: Fundamentals_of_Programming/ch7.md
    - ch8 非文本数据处理: Fundamentals_of_Programming/ch8.md
    - ch9 可配置的程序设计: Fundamentals_of_Programming/ch9.md
  - 面向对象: 
    - 课程简介: Object_Oriented_Programming/index.md
    - ch1 编程环境: Object_Oriented_Programming/ch1.md
    - ch2 基础语法(1): Object_Oriented_Programming/ch2.md
    - ch3 基础语法(2): Object_Oriented_Programming/ch3.md
    - ch4 基础语法(3): Object_Oriented_Programming/ch4.md
    - ch5 找到对象,确定接口: Object_Oriented_Programming/ch5.md
    - ch6 算法横向拆分,分离步骤: Object_Oriented_Programming/ch6.md
    - ch7 算法纵向拆分,分离表示: Object_Oriented_Programming/ch7.md
    - ch8 基于接口组合,应对复杂变化: Object_Oriented_Programming/ch8.md
    - ch9 增加抽象层级,隔离复杂变化: Object_Oriented_Programming/ch9.md
  - 离散数学: 
    - 课程简介: Discrete_Mathematics/index.md
    - ch1 命题逻辑的基本概念: Discrete_Mathematics/ch1.md
    - ch2 命题逻辑的推理演算: Discrete_Mathematics/ch2.md
    - ch3 命题逻辑的公理化: Discrete_Mathematics/ch3.md
    - ch4 谓词逻辑的基本概念: Discrete_Mathematics/ch4.md
    - ch5 谓词逻辑的推理演算: Discrete_Mathematics/ch5.md
    - ch6 集合: Discrete_Mathematics/ch6.md
    - ch7 关系: Discrete_Mathematics/ch7.md
    - ch8 函数: Discrete_Mathematics/ch8.md
    - ch9 实数集合: Discrete_Mathematics/ch9.md
  - 数据结构: 
    - 课程简介: Data_Structure/index.md
    - ch1 绪论: Data_Structure/ch1.md
    - ch2 向量: Data_Structure/ch2.md
    - ch3 列表: Data_Structure/ch3.md
    - ch4 栈与队列: Data_Structure/ch4.md
    - ch5 二叉树: Data_Structure/ch5.md
    - ch6 图: Data_Structure/ch6.md
    - ch7 图应用: Data_Structure/ch7.md
    - ch8 二叉搜索树: Data_Structure/ch8.md
    - ch9 高级搜索树: Data_Structure/ch9.md
    - ch10 词典: Data_Structure/ch10.md
    - ch11 优先级队列: Data_Structure/ch11.md
    - ch12 串: Data_Structure/ch12.md
    - ch13 排序: Data_Structure/ch13.md
  - 计组原理: 
    - 课程简介: Principles_of_Computer_Organization/index.md
  - 算法分析: 
    - 课程简介: Algorithm_Design_and_Analysis/index.md
  - 操作系统: 
    - 课程简介: Operating_System/index.md
  - 计算机网络: 
    - 课程简介: Operating_System/index.md
  - 数据库系统: 
    - 课程简介: Principles_and_Development_of_Database_Systems/index.md
  - 编译原理: 
    - 课程简介: Compiler_Principle/index.md
  - 软件工程: 
    - 课程简介: Software_Engineering/index.md
  - 机器学习概论: 
    - 课程简介: Introduction_to_Machine_Learning/index.md
    - ch 1 绪论: Introduction_to_Machine_Learning/ch1.md
    - ch 2 决策树学习: Introduction_to_Machine_Learning/ch2.md
    - ch 3 贝叶斯学习: Introduction_to_Machine_Learning/ch3.md
    - ch 4 马尔可夫模型: Introduction_to_Machine_Learning/ch4.md
    - ch 5 假设检验: Introduction_to_Machine_Learning/ch5.md
    - ch 6 基于实例的学习: Introduction_to_Machine_Learning/ch6.md
    - ch 7 支持向量机: Introduction_to_Machine_Learning/ch7.md
    - ch 8 无监督学习: Introduction_to_Machine_Learning/ch8.md
  - 人工智能原理: 
    - 课程简介: Principles_of_Artificial_Intelligence/index.md

theme:
  icon:
    logo: material/home
  name: material
  language: zh
  palette:
    # 亮色
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: 亮色
     
    # 暗色
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: 暗色
    
  features:
    - navigation.instant # 单页应用
    - navigation.tabs # 页面上方的标签页
    - navigation.tracking # 页面滚动时，导航栏高亮当前页面
    - navigation.sections # 使导航栏分块
    - navigation.expand # 默认展开导航
    - navigation.prune # 只渲染当前页面的导航
    - toc.follow # 滚动的时候侧边栏自动跟随
    - navigation.top # 返回顶部按钮
    - search.suggest # 补全建议
    - search.highlight # 搜索结果高亮
    - search.share # 搜索结果分享
    - navigation.footer # 页脚提示下一章
    - content.code.copy # 代码段上的赋值按钮

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  # - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.highlight:  # 代码高亮
      anchor_linenums: true
  - admonition # 警告语法
  - def_list
  - footnotes
  - abbr
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - md_in_html
  - pymdownx.arithmatex: # latex支持
      generic: true
  - toc:
      permalink: true # 固定标题位置为当前位置
      toc_depth: 3 # 目录深度
  - pymdownx.highlight: # 代码块高亮
      anchor_linenums: true
      linenums: true # 显示行号
      use_pygments: true # 代码高亮
      pygments_lang_class: true
      auto_title: true # 显示编程语言名称
      linenums_style: pymdownx-inline # 行号样式,防止复制的时候复制行号
  - pymdownx.betterem # 强调美化,比如**text**会被美化
  - pymdownx.caret # 上标和下标
  - pymdownx.mark # 上标和下标
  - pymdownx.tilde # 上标和下标
  - pymdownx.keys # 显示按键组合
  - pymdownx.critic
  - pymdownx.details # 可以折叠的代码块 ??? note 可以让警告变成折叠的
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.magiclink # 自动识别链接
  - pymdownx.smartsymbols # 智能符号
  - pymdownx.snippets # 代码段
  - pymdownx.tasklist:
      custom_checkbox: true # 自定义复选框
  - attr_list
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:material.extensions.emoji.twemoji
  #     emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences: # 代码块中支持 Mermaid
      custom_fences: # 支持 Mermaid
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - meta # 支持Markdown文件上方自定义标题标签等
  - tables

extra:
  generator: false  #删除页脚显示“使用 MkDocs 材料制造”
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ErnestEarth/jifeng
      name: GitHub
    # - icon: fontawesome/brands/bilibili
    #   link: https://space.bilibili.com/294675129
    #   name: Bilibili
    # - icon: material/email
    #   link: soulio:<doureamon@163.com>
    #   name: Email